### ISSUE TITLE
Consider adding reinstall command

### ISSUE THREAD

**Issue by Botspot** [Itai-Nelken/PiApps-terminal_bash-edition#1]
This would be a simple shorthand to save time.
Consider making a new `reinstall` command to first `uninstall`, then `install`.

Concerning error-exiting for this new command, I think the `uninstall` part should be non-fatal, but the `install` part should be fatal.

**Comment by Itai-Nelken** [comment]
added in f53ce2710f9e0120474b4c62898e44d91ddf0c47
