### ISSUE TITLE
reinstall command does not work

### ISSUE THREAD

**Issue by Botspot** [Itai-Nelken/PiApps-terminal_bash-edition#2]
Reinstalling does not work:
```
$ pi-apps reinstall 'Min Browser'
/home/pi/pi-apps/apps/Min Browser  does not exist!
/home/pi/pi-apps/apps/Min Browser  does not exist!
Failed to reinstall "Min Browser "!
```
But uninstalling does.
```
$ pi-apps uninstall 'Min Browser'
Uninstalling Min Browser...
```
Removing the space character from line 181 fixes the problem, but breaks the functionality for multiple apps to be reinstalled.

**Comment by Itai-Nelken** [comment]
I made the script remove the last character from the `cmdflags` variable using this bash trick: `var=${var::-1}` (remove the 1 last character from `var`).

**Comment by Itai-Nelken** [comment]
also the `reinstall` command doesn't support multiple apps, it supports providing app names with spaces without quotes.
for example: `pi-apps reinstall Min Browser` instead of `pi-apps reinstall 'Min Browser'`.
